services:
  odoo:
    image: odoo:18
    container_name: odoo18-app
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt
      - ./data/odoo:/var/lib/odoo
      - ./entrypoint.sh:/entrypoint.sh
    env_file: .env
    entrypoint: ["/entrypoint.sh"]
    stdin_open: true
    tty: true
  db:
    image: postgres:15
    container_name: odoo18-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports: 
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
  pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin18-db
        env_file: .env
        environment: 
          - PGADMIN_DEFAULT_EMAIL=${PGA_EMAIL}
          - PGADMIN_DEFAULT_PASSWORD=${PGA_PASSWORD}
        ports: 
          - "5019:80"
        volumes:
          - ./data/pgadmin:/var/lib/pgadmin